project: northwind-platform
environment: prd
tenantMode: target-enterprise
tenantDomain: varundhiman08outlook.onmicrosoft.com
region: canada-central
workspacePattern: "ws-npw-{domain}-prd"
git:
  provider: github
  branch: master
capacity:
  type: dedicated
  targetSku: F8-or-higher
